# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/dnephin/pre-commit-golang
    rev: v0.5.1
    hooks:
      - id: go-cyclo
        args: [-over=15]
      - id: go-unit-tests
      - id: go-mod-tidy
